Initial plugin implementation
silvermine/videojs-airplay pull request #1
Opened 2017-07-14 19:17 UTC by yokuze

2017-08-04 17:58 UTC, jthomerson requested changes
Please also add some simple documentation in the form of an example. You can mimic what @onebytegone did in https://github.com/silvermine/videojs-quality-selector/pull/1/files since it's simple and accomplishes the purpose.

2017-08-04 17:58 UTC, jthomerson commented on Gruntfile.js
> +   grunt.registerTask('build', [ 'build-js', 'build-css', 'copy:images' ]);
Can we add a `develop` task that builds and watches for changes? It should basically cover the 95% usecase for what a developer wants to do when he's working on this repo.

2017-08-04 17:58 UTC, jthomerson commented on package.json
>      "test": "./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha -- -R spec 'tests/**/*.test.js'"
Please add a `prepublish` script that builds the minified versions, as @onebytegone did at https://github.com/silvermine/videojs-quality-selector/pull/1/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R7

2017-08-04 17:58 UTC, jthomerson commented on src/images/ic_airplay_black_24px.svg
> +</svg>
Can you go ahead and fix the missing trailing newline on the SVGs that are missing it? Seems that one has it and two don't.

2017-08-04 17:58 UTC, jthomerson commented on src/js/browser.js
> +'use strict';
Please add a comment to this file indicating what it's used for.

2017-08-04 17:58 UTC, jthomerson commented on src/js/enableAirPlay.js
> +}
Why is this function duplicated in two files?

2017-08-04 18:11 UTC, jthomerson commented on package.json
> +    "browserify-shim": "3.8.14"
Should this be a `devDependency`?

https://github.com/thlorenz/browserify-shim#you-will-always

2017-08-09 19:56 UTC, yokuze commented
Alright @jthomerson, I think I've addressed your comments. Thanks.

2017-08-09 20:25 UTC, yokuze commented
Sorry about that - had a whitespace issue that caused `eslint` to fail.

2017-08-09 20:45 UTC, merged