Add README and jsdoc documentation
silvermine/videojs-airplay pull request #2
Opened 2017-08-10 22:39 UTC by yokuze

Additionally, change the interface of the enableAirPlay function
for clarity (passing the videojs player instance as a parameter
rather than relying on it implicitly being the `this` context).

2017-08-11 02:23 UTC, jthomerson requested changes

2017-08-11 02:23 UTC, jthomerson commented on src/js/enableAirPlay.js
> + * Adds the AirPlayButton Component to the player's ControlBar component, if the
"if the {what}"?

2017-08-11 02:24 UTC, jthomerson commented
@yokuze just the one minor thing

2017-08-15 12:22 UTC, yokuze commented on src/js/enableAirPlay.js
> + * Adds the AirPlayButton Component to the player's ControlBar component, if the
Fixed. Thanks!

2017-08-15 13:15 UTC, jthomerson approved these changes

2017-08-15 13:15 UTC, merged