chore: Update Node to 12.14.0 and NPM to 6.13.4
silvermine/videojs-airplay pull request #22
Opened 2020-02-11 21:04 UTC by pbredenberg

Also updates some needed npm dependencies, and adds commitlint.

2020-02-12 14:56 UTC, yokuze requested changes

2020-02-12 14:56 UTC, yokuze commented on .nvmrc
> +12.14.0
This should be 12.13.1

2020-02-12 15:16 UTC, yokuze commented on .nvmrc
> +12.14.0
Oops, sorry @pbredenberg. @jthomerson filled me in that we will be upgrading to 12.14.0 now.

2020-02-14 14:19 UTC, yokuze approved these changes
Looks good.

2020-02-14 14:22 UTC, onebytegone approved these changes

2020-02-14 14:22 UTC, merged