Upgrade to Node 20.12.2
silvermine/videojs-airplay pull request #54
Opened 2024-06-23 15:24 UTC by joshuacurtiss

In addition to upgrading the project to Node 20.12.2, including its GitHub Actions job, we also made these adjustments:

When regenerating the `package-lock.json` file, `browserslist` made updates that cause Babel processing to *allow* `const` in the transformed output. (This is due to our `NOT DEAD` rule in Babel and how it is interacting with the latest browser data from `browserslist`.) As a result, uglification was throwing errors:

```
Warning: Uglification failed.
Unexpected token: keyword (const).
```

Upgrading `grunt-contrib-uglify` to v4.0.1 resolves the uglification error.

It was also noted that the uglification settings were set to mangle/compress in debug mode and beautify in production mode. Presumably, this was intended to be the reverse.

2024-06-23 18:03 UTC, Timodie commented
Will we need to bump up the version number as part of the node upgrade?
I noticed that the version bump followed the node upgrade in some of the other [projects](https://github.com/silvermine/toolbox/commit/a23a5dbe5ce1c8a1274aad7a226f2b88af0c8f8d)

2024-06-23 22:43 UTC, onebytegone commented
> Will we need to bump up the version number as part of the node upgrade? I noticed that the version bump followed the node upgrade in some of the other [projects](https://github.com/silvermine/toolbox/commit/a23a5dbe5ce1c8a1274aad7a226f2b88af0c8f8d)

@Timodie Yes, once this PR is merged and if no additional changes are needed, we'll cut a new version of this package. We don't typically have a version bump in the same PR as other changes.

2024-06-30 15:42 UTC, joshuacurtiss commented
I updated the PR description (after a closer before/after examination of the `browserslist` output after regenerating the package-lock.json) to explain that `const` being passed through Babel's output is due to `browserslist` removing `safari 9.1`, which only has partial support for `const`.

I was unsure if this change in Babel output would be acceptable, but if according to caniuse/browserslist/babel it is safe to use `const` when Safari 9.1 is eliminated, then our new built artifacts containing `const` should be alright, given that our current desired Safari support is _iOS Safari 12.2_.

CC: @kmuncie

2024-07-18 22:42 UTC, joshuacurtiss commented
@onebytegone, would you mind giving me your thoughts on 80d826ecc3f1209dd03f52b0081492b60990a5b6? Namely:

- Incorporating the `.nvmrc` version into the test matrix
- Using `git status --porcelain` to check for uncommitted changes

I'm just checking that this particular approach is what you had in mind for accomplishing these two goals in GitHub Actions jobs.

2024-07-19 18:02 UTC, joshuacurtiss commented
> * Using `git status --porcelain` to check for uncommitted changes

Come to think of it, there's a case for saying that the "uncommitted changes" step should be last in the `build` job, in the unlikely event that even standards checks or other tests have compromised code..

2024-07-22 19:33 UTC, onebytegone requested changes

2024-07-22 19:33 UTC, onebytegone commented on .github/workflows/ci.yml
> +         -  uses: actions/checkout@v4
Unless it's a single key, we typically put the keys on separate lines:

```suggestion
         -
            uses: actions/checkout@v3
```

2024-07-22 19:33 UTC, onebytegone commented on .github/workflows/ci.yml
> +         -  run: npm ci
For single keys, we'll typically only have one space after the dash.

```suggestion
         - run: npm ci
```

2024-07-22 19:33 UTC, onebytegone commented on .github/workflows/ci.yml
> +            uses: coverallsapp/github-action@v2
This should probably become a parallel job like we did in https://github.com/silvermine/toolbox/commit/011506189f1db4e2ca7c2b870fd7fc08a4ed298e

2024-07-22 19:33 UTC, onebytegone commented on .github/workflows/ci.yml
> +         -  run: npm run standards
```suggestion
         -  run: npm run standards
         -  run: npm run build
```

2024-07-22 19:33 UTC, onebytegone commented on .github/workflows/ci.yml
> +         -  run: npm test
```suggestion
         -  run: npm run build # Ensure building is possible with this version of node
         -  run: npm test
```

2024-07-25 21:21 UTC, joshuacurtiss commented
@onebytegone Ok, made all suggested changes.. 

Note I also moved the "uncommitted changes" check as the last step of the `build` job, since it makes more sense to be last.

Also note... to serve as an example, it makes sense to add `npm run build`. However, this particular repo has a `prepublish` script which runs a build.  Since `prepublish` runs on npm install, the project is technically already built with the `npm ci` command. Just wanted to point that out before we proceed!

2024-07-26 15:31 UTC, onebytegone approved these changes

2024-07-26 15:32 UTC, merged